# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  apigateway.yarp:
    build:
      context: "C:\\Projects\\EventBookingService\\src\\EventBookingService"
      dockerfile: "ApiGateways/YarpApiGateway/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "apigateway.yarp:dev"
    ports:
    - "127.0.0.1:57000:57100"
    - "127.0.0.1:57200:57300"
    volumes:
    - "C:\\Users\\quang\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Projects\\EventBookingService\\src\\EventBookingService\\ApiGateways\\\
      YarpApiGateway:/app:rw"
    - "C:\\Projects\\EventBookingService\\src\\EventBookingService:/src:rw"
    - "C:\\Users\\quang\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.4\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2.3\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\quang\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_9_18_14_55_29:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  booking.api:
    build:
      context: "C:\\Projects\\EventBookingService\\src\\EventBookingService"
      dockerfile: "Services/Booking/Booking.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "bookingapi:dev"
    ports:
    - "127.0.0.1:57001:57100"
    - "127.0.0.1:57201:57300"
    volumes:
    - "C:\\Users\\quang\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Projects\\EventBookingService\\src\\EventBookingService\\Services\\Booking\\\
      Booking.API:/app:rw"
    - "C:\\Projects\\EventBookingService\\src\\EventBookingService:/src:rw"
    - "C:\\Users\\quang\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.4\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2.3\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\quang\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_9_18_14_55_29:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  eventbooking.basket:
    build:
      context: "C:\\Projects\\EventBookingService\\src\\EventBookingService"
      dockerfile: "Services/Basket/EventBooking.Basket/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "eventbookingbasket:dev"
    ports:
    - "127.0.0.1:57002:57100"
    - "127.0.0.1:57202:57300"
    volumes:
    - "C:\\Users\\quang\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Projects\\EventBookingService\\src\\EventBookingService\\Services\\Basket\\\
      EventBooking.Basket:/app:rw"
    - "C:\\Projects\\EventBookingService\\src\\EventBookingService:/src:rw"
    - "C:\\Users\\quang\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.4\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2.3\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\quang\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_9_18_14_55_29:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  eventbooking.discount:
    build:
      context: "C:\\Projects\\EventBookingService\\src\\EventBookingService"
      dockerfile: "Services/Discount/EventBooking.Discount/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "eventbookingdiscount:dev"
    ports:
    - "127.0.0.1:57003:57100"
    - "127.0.0.1:57203:57300"
    volumes:
    - "C:\\Users\\quang\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Projects\\EventBookingService\\src\\EventBookingService\\Services\\Discount\\\
      EventBooking.Discount:/app:rw"
    - "C:\\Projects\\EventBookingService\\src\\EventBookingService:/src:rw"
    - "C:\\Users\\quang\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.4\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2.3\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\quang\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_9_18_14_55_29:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  eventbooking.event:
    build:
      context: "C:\\Projects\\EventBookingService\\src\\EventBookingService"
      dockerfile: "Services/Event/EventBooking.Event/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "eventbookingevent:dev"
    ports:
    - "127.0.0.1:57004:57100"
    - "127.0.0.1:57204:57300"
    volumes:
    - "C:\\Users\\quang\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Projects\\EventBookingService\\src\\EventBookingService\\Services\\Event\\\
      EventBooking.Event:/app:rw"
    - "C:\\Projects\\EventBookingService\\src\\EventBookingService:/src:rw"
    - "C:\\Users\\quang\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.4\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2.3\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\quang\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_9_18_14_55_29:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  eventbooking.notification:
    build:
      context: "C:\\Projects\\EventBookingService\\src\\EventBookingService"
      dockerfile: "Services/Notification/EventBooking.Notification/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "eventbookingnotification:dev"
    ports:
    - "127.0.0.1:57005:57100"
    - "127.0.0.1:57205:57300"
    volumes:
    - "C:\\Users\\quang\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Projects\\EventBookingService\\src\\EventBookingService\\Services\\Notification\\\
      EventBooking.Notification:/app:rw"
    - "C:\\Projects\\EventBookingService\\src\\EventBookingService:/src:rw"
    - "C:\\Users\\quang\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.4\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2.3\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\quang\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_9_18_14_55_29:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  eventbooking.payment:
    build:
      context: "C:\\Projects\\EventBookingService\\src\\EventBookingService"
      dockerfile: "Services/Payment/EventBooking.Payment/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "eventbookingpayment:dev"
    ports:
    - "127.0.0.1:57006:57100"
    - "127.0.0.1:57206:57300"
    volumes:
    - "C:\\Users\\quang\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Projects\\EventBookingService\\src\\EventBookingService\\Services\\Payment\\\
      EventBooking.Payment:/app:rw"
    - "C:\\Projects\\EventBookingService\\src\\EventBookingService:/src:rw"
    - "C:\\Users\\quang\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.4\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2.3\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\quang\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_9_18_14_55_29:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  eventbooking.web:
    build:
      context: "C:\\Projects\\EventBookingService\\src\\EventBookingService\\WebApps\\\
        EventBooking.Web"
      dockerfile: "Dockerfile"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-musl-x64/dotnet/dotnet"
    - "exec"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "eventbookingweb:dev"
    ports:
    - "127.0.0.1:57007:57100"
    - "127.0.0.1:57207:57300"
    volumes:
    - "C:\\Users\\quang\\.nuget\\packages:/root/.nuget/packages"
    - "C:\\Projects\\EventBookingService\\src\\EventBookingService\\WebApps\\Eventbooking.Web:/app-1:rw"
    - "C:\\Projects\\EventBookingService\\src\\EventBookingService:/src:rw"
    - "C:\\Users\\quang\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.4\\\
      LinuxMusl64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2.3\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\quang\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_9_18_14_55_29:/var/opt/rider-debugger:rw"
    working_dir: "/app-1"
