version: '3.4'

services:
  eventdb:
    image: postgres

  basketdb:
    image: postgres
    
  bookingdb:
    image: mysql

  distributedcache:
    image: redis

  eventbooking.event:
    image: ${DOCKER_REGISTRY-}eventbookingevent
    build:
      context: .
      dockerfile: Services/Event/EventBooking.Event/Dockerfile
   
  eventbooking.basket:
    image: ${DOCKER_REGISTRY-}eventbookingbasket
    build:
      context: .
      dockerfile: Services/Basket/EventBooking.Basket/Dockerfile

  eventbooking.discount:
    image: ${DOCKER_REGISTRY-}eventbookingdiscount
    build:
      context: .
      dockerfile: Services/Discount/EventBooking.Discount/Dockerfile
      
  booking.api:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: Services/Booking/Booking.API/Dockerfile
      
  eventbooking.notification:
    image: ${DOCKER_REGISTRY-}eventbookingnotification
    build:
      context: .
      dockerfile: Services/Notification/EventBooking.Notification/Dockerfile    
      
  eventbooking.web:
    image: ${DOCKER_REGISTRY-}eventbookingweb
    build:
      context: ./WebApps/EventBooking.Web
      dockerfile: Dockerfile
    env_file:
      - ./WebApps/EventBooking.Web/.env    

  keycloakdb:
    image: postgres:16

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
        
  messagebroker:
    image: rabbitmq:management

volumes:
  postgres_event:
  postgres_basket:  
  mysql_booking:  
  postgres_keycloak:
  keycloak:






