version: '3.4'

services:
  eventdb:
    image: postgres

  basketdb:
    image: postgres

  distributedcache:
    image: redis

  eventbooking.event:
    image: ${DOCKER_REGISTRY-}eventbookingevent
    build:
      context: .
      dockerfile: Services/Event/EventBooking.Event/Dockerfile
   
  eventbooking.basket:
    image: ${DOCKER_REGISTRY-}eventbookingbasket
    build:
      context: .
      dockerfile: Services/Basket/EventBooking.Basket/Dockerfile

  keycloakdb:
    image: postgres:16

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4

  eventbooking.web:
    image: ${DOCKER_REGISTRY-}eventbookingweb
    build:
      context: ./WebApps/EventBooking.Web
      dockerfile: Dockerfile
    env_file:
      - ./WebApps/EventBooking.Web/.env

volumes:
  postgres_event:
  postgres_basket:  
  postgres_keycloak:
  keycloak:



