version: '3.4'

services:
  eventdb:
    image: postgres

  distributedcache:
    image: redis

  eventbooking.event:
    image: ${DOCKER_REGISTRY-}eventbookingevent
    build:
      context: .
      dockerfile: EventBooking.Event/Dockerfile

  keycloakdb:
    image: postgres:16

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4

volumes:
  postgres_event:    
  postgres_keycloak:
  keycloak:
