version: '3.4'

services:
  eventdb:
    container_name: eventdb
    environment:
      - POSTGRES_DB=EventDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_event:/var/lib/postgresql/data
        
  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_DB=BasketDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data      
        
  bookingdb:
    container_name: bookingdb
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=BookingDb
    ports:
      - "3307:3306"
    volumes:
      - mysql_booking:/var/lib/mysql

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  eventbooking.event:
    container_name: eventbooking.event
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=eventdb;Port=5432;Database=EventDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
      - MessageBroker__Host=amqp://eventbooking-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - Keycloak__Authority=http://keycloak:8090/realms/Event-Booking-Service
      - Keycloak__MetadataAddress=http://keycloak:8090/realms/Event-Booking-Service/.well-known/openid-configuration
      - Keycloak__RequireHttpsMetadata=false
      - Keycloak__ValidIssuers=["http://keycloak:8090/realms/Event-Booking-Service"]
      - Keycloak__Audience=event_service
      - Keycloak__ValidAudiences=["event_service"]
      - Keycloak__ClientIdStorage=event-booking-service-storage
      - Keycloak__ClientSecretStorage=MUvacGIi9xvCaz3G0iWq4YoKA9Gwo6EG
      - Keycloak__TokenEndpoint=http://keycloak:8090/realms/Event-Booking-Service/protocol/openid-connect/token
      - GrpcSettings__StorageUrl=https://eventbooking.storage:8081
    depends_on:
      - eventdb
      - distributedcache
      - keycloak 
      - messagebroker
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  
  eventbooking.basket:
    container_name: eventbooking.basket
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcSettings__DiscountUrl=https://eventbooking.discount:8081
      - MessageBroker__Host=amqp://eventbooking-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - Keycloak__Authority=http://keycloak:8090/realms/Event-Booking-Service
      - Keycloak__MetadataAddress=http://keycloak:8090/realms/Event-Booking-Service/.well-known/openid-configuration
      - Keycloak__RequireHttpsMetadata=false
      - Keycloak__ValidIssuers=["http://keycloak:8090/realms/Event-Booking-Service"]
      - Keycloak__Audience__webapp=basket_service
      - Keycloak__Audience__basket_service=payment_service
      - Keycloak__ValidAudiences__webapp=["basket_service"]
      - Keycloak__ValidAudiences__basket_service=["payment_service"]
    depends_on:
      - basketdb
      - distributedcache
      - keycloak
      - eventbooking.event
      - messagebroker
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  
  eventbooking.discount:
    container_name: eventbooking.discount
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Data Source=discountdb
    depends_on:
      - eventbooking.basket
    ports:
      - "6003:8080"
      - "6063:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
        
  booking.api:
    container_name: booking.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=bookingdb;Port=3306;Database=BookingDb;Uid=root;Pwd=root;
      - MessageBroker__Host=amqp://eventbooking-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - Keycloak__Authority=http://keycloak:8090/realms/Event-Booking-Service
      - Keycloak__MetadataAddress=http://keycloak:8090/realms/Event-Booking-Service/.well-known/openid-configuration
      - Keycloak__RequireHttpsMetadata=false
      - Keycloak__ValidIssuers=["http://keycloak:8090/realms/Event-Booking-Service"]
      - Keycloak__Audience=booking_service
      - Keycloak__ValidAudiences=["booking_service"]
    depends_on:
      - bookingdb
      - messagebroker
      - keycloak
    ports:
      - "6004:8080"
      - "6064:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro     
      
  eventbooking.notification:
    container_name: eventbooking.notification
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - MessageBroker__Host=amqp://eventbooking-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - Keycloak__Authority=http://keycloak:8090/realms/Event-Booking-Service
      - Keycloak__MetadataAddress=http://keycloak:8090/realms/Event-Booking-Service/.well-known/openid-configuration
      - Keycloak__RequireHttpsMetadata=false
      - Keycloak__ValidIssuers=["http://keycloak:8090/realms/Event-Booking-Service"]
      - Keycloak__Audience=notification_service
      - Keycloak__ValidAudiences=["notification_service"]
    depends_on:
      - eventbooking.event
      - distributedcache
      - messagebroker
      - keycloak
      - eventbooking.basket
    ports:
      - "6005:8080"
      - "6065:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      
  eventbooking.payment:
    container_name: eventbooking.payment
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - MessageBroker__Host=amqp://eventbooking-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - Keycloak__Authority=http://keycloak:8090/realms/Event-Booking-Service
      - Keycloak__MetadataAddress=http://keycloak:8090/realms/Event-Booking-Service/.well-known/openid-configuration
      - Keycloak__RequireHttpsMetadata=false
      - Keycloak__ValidIssuers=["http://keycloak:8090/realms/Event-Booking-Service"]
      - Keycloak__Audience=payment_service
      - Keycloak__ValidAudiences=["payment_service"]
      - Keycloak__ClientId=event-booking-service-basket
      - Keycloak__ClientSecret=SdxYSONTBRPka1SjHw4DAFiPbCh45V4x
      - Keycloak__TokenEndpoint=http://keycloak:8090/realms/Event-Booking-Service/protocol/openid-connect/token
      - GrpcSettings__BasketUrl=https://eventbooking.basket:8081
    depends_on:
      - eventbooking.basket
      - messagebroker
      - keycloak
    ports:
      - "6006:8080"
      - "6066:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro    
        
  stripe.cli:
    container_name: stripe.cli
    network_mode: host
    depends_on:
      - eventbooking.payment
    environment:
      - STRIPE_API_KEY=sk_test_51PcP70RoqHqSv3QAWHTPNVCVkcxDwZ5L3MQM1zPTjjJMMvozvzcmJTOlBT1EW9XkEt51ozXRYfIPhcuQnZn0obhj00kvvEcFZp
    command: listen --forward-to http://localhost:6006/fullfilment
        
  eventbooking.web:
    container_name: eventbooking.web
    build:
      context: ./WebApps/EventBooking.Web
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - VITE_AUTHORITY=http://localhost:8090/realms/Event-Booking-Service
      - VITE_REDIRECT_URI=http://localhost:3000/signin-callback.html
      - VITE_NOTIFICATIONS_API=https://localhost:6065/notifications
      - VITE_CHECKOUT_API=https://localhost:6067/payment-service/checkout
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./WebApps/EventBooking.Web:/app
      - /app/node_modules
    depends_on:
      - eventdb
      - distributedcache
      - keycloak
      - eventbooking.event
      - eventbooking.basket
      - eventbooking.discount
      - eventbooking.notification
      - booking.api
  
  keycloakdb:
    container_name: keycloakdb
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_keycloak:/var/lib/postgresql/data

  keycloak:
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloakdb
      - KC_DB_DATABASE=keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_HTTP_PORT=8090
      # - KC_FEATURES=hostname:v2
      # - KC_HOSTNAME=https://keycloak.example.com
      # - KC_HTTP_ENABLED=true
      # - KC_HOSTNAME_ADMIN=https://admin.keycloak.example.com
    restart: always
    depends_on:
      - keycloakdb
    command: "start-dev --import-realm"
    ports:
      - "8090:8090"
    volumes:
      - keycloak:/opt/keycloak/data/import
  
  messagebroker:
    container_name: messagebroker
    hostname: eventbooking-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  yarpapigateway:
    container_name: yarpapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Keycloak__Authority=http://keycloak:8090/realms/Event-Booking-Service
      - Keycloak__MetadataAddress=http://keycloak:8090/realms/Event-Booking-Service/.well-known/openid-configuration
      - Keycloak__RequireHttpsMetadata=false
      - Keycloak__ValidIssuers=["http://keycloak:8090/realms/Event-Booking-Service"]
      - Keycloak__Audience__webapp=api_gateway
      - Keycloak__ValidAudiences__webapp=["api_gateway"]
      - ReverseProxy__Clusters__event-cluster__Destinations__destination1__Address=http://eventbooking.event:8080
      - ReverseProxy__Clusters__basket-cluster__Destinations__destination1__Address=http://eventbooking.basket:8080
      - ReverseProxy__Clusters__booking-cluster__Destinations__destination1__Address=http://booking.api:8080
      - ReverseProxy__Clusters__payment-cluster__Destinations__destination1__Address=http://eventbooking.payment:8080
    depends_on:
      - eventbooking.event
      - eventbooking.basket
      - eventbooking.payment
      - booking.api
    ports:
      - "6007:8080"
      - "6067:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
