version: '3.4'

services:
  eventdb:
    image: postgres

  distributedcache:
    image: redis

  eventbooking.event:
    image: ${DOCKER_REGISTRY-}eventbookingevent
    build:
      context: .
      dockerfile: EventBooking.Event/Dockerfile

volumes:
  postgres_event:    
  

