// <auto-generated />
using EventBooking.Discount.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventBooking.Discount.Migrations
{
    [DbContext(typeof(DiscountContext))]
    partial class DiscountContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("EventBooking.Discount.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Event 1 Description",
                            DiscountPercentage = 10,
                            EventName = "Event 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Event 2 Description",
                            DiscountPercentage = 20,
                            EventName = "Event 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Event 3 Description",
                            DiscountPercentage = 30,
                            EventName = "Event 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
